language: java

sudo: required

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

install:
  #- ./src/main/bash/install_dspot.sh
  - export MAVEN_HOME=/usr/local/maven-3.5.0

script:
  #- ./src/main/bash/run-mutant-original.sh
  #- ./src/main/bash/amplification.sh
  #- ./src/main/bash/run-mutant-amplified.sh